version: '3.11'

services:
  mongodb:
    image: mongo:7
    container_name: chronos_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chronos_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chronos_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chronos_db
      - SECRET_KEY=tu_secreto_super_seguro_aqui_cambialo_por_algo_real
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/app/__pycache__

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chronos_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data: